name:                purescm
version:             0.1.0.0
github:              "githubuser/purescm"
license:             GPL-2
author:              "Tancredi Orlando"
maintainer:          ""
copyright:           "2021 Tancredi Orlando"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/purescm#readme>

dependencies:
- base >= 4.7 && < 5
- purescript
- purescript-ast
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints

default-extensions:
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving

library:
  source-dirs: src

executables:
  purescm-exe:
    main:                Main.hs
    source-dirs:         app

    dependencies:
    - purescm

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  purescm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purescm
