name:                purescm
version:             0.1.0.0
github:              "githubuser/purescm"
license:             GPL-2
author:              "Tancredi Orlando"
maintainer:          ""
copyright:           "2021 Tancredi Orlando"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/purescm#readme>

dependencies:
  - base >= 4.7 && < 5
  - purescript
  - purescript-ast
  - aeson

library:
  source-dirs: src

executables:
  purescm-exe:
    main:                Main.hs
    source-dirs:         app

    dependencies:
      - purescm

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wredundant-constraints

tests:
  purescm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purescm
