name: purescm
version: "0.0.1"

license: AGPL-3
license-file: LICENSE.txt
copyright: 2021 Tancredi Orlando

author:
- Tancredi Orlando <tancredi.orlando@gmail.com>
- Fabrizio Ferrai <fabrizio.ferrai@gmail.com>

maintainer:
- Tancredi Orlando <tancredi.orlando@gmail.com>
- Fabrizio Ferrai <fabrizio.ferrai@gmail.com>

homepage: https://github.com/turlando/purescm
github: turlando/purescm

description: |
  Scheme backend for PureScript (a small strongly, statically typed programming
  language with expressive types, inspired by Haskell).

extra-source-files:
- stack.yaml
- README.md
- LICENSE.txt

dependencies:
- base >= 4.7 && < 5
- aeson
- directory
- foldl
- optparse-applicative
- prettyprinter
- process
- purescript
- purescript-cst
- text
- turtle

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints

default-extensions:
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving

library:
  source-dirs: src

executables:
  purescm:
    main: Main.hs
    source-dirs: app

    dependencies:
    - purescm

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  spec:
    defaults: hspec/hspec@master

    dependencies:
    - purescm

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    # Make purescm binary available in test runner PATH
    build-tools:
    - purescm
