resolver: lts-17.10

packages:
  - .

extra-deps:
- random-1.2.1
# Purescript wants this version
- language-javascript-0.7.0.0

- github: purescript/purescript
  commit: v0.14.4
  subdirs:
    - lib/purescript-cst
    - '.'

nix:
  shell-file: stack-shell.nix
