(import (chezscheme)
        (only (purescm finalizers) run-finalizers)
        (only (purescm stack-trace) print-stack-trace)
        (only (purescm test pstring-test) main))
(collect-request-handler (lambda () (collect) (run-finalizers)))
(base-exception-handler (lambda (e) (print-stack-trace e) (exit -1)))
(display "Testing pstring\n")
(main)
(display "All good!\n")
