#!/usr/bin/env -S scheme --libdirs vendor: --program
(import (chezscheme)
        (only (purs runtime finalizers) run-finalizers)
        (only (purs runtime stack-trace) print-stack-trace)
        (only (purs runtime test pstring-test) main))
(collect-request-handler (lambda () (collect) (run-finalizers)))
(base-exception-handler (lambda (e) (print-stack-trace e) (exit -1)))
(display "Testing pstring\n")
(main)
(display "All good!\n")
