;; DO NOT EDIT THIS FILE!!
;; This inlined chez-srfi library code is autogenerated using command:
;; $ ./install.chezscheme.sps ../vendor/
;; Source origin: https://github.com/arcfide/chez-srfi
;; Please refer to project site for full credits and original code.
;;;;;; File header: %3a23.sls
#!r6rs
;; Automatically generated by private/make-aliased-libraries.sps
(library (srfi :23)
  (export error)
  (import (srfi :23 error)))
