;; DO NOT EDIT THIS FILE!!
;; This inlined chez-srfi library code is autogenerated using command:
;; $ ./install.chezscheme.sps ../lib
;; Source origin: https://github.com/arcfide/chez-srfi
;; Please refer to project site for full credits and original code.
;;;;;; File header: %3a0/cond-expand.guile.sls
(library (srfi srfi-0)
  (export cond-expand)
  (import (only (guile) cond-expand)))
