;; DO NOT EDIT THIS FILE!!
;; This inlined chez-srfi library code is autogenerated using command:
;; $ ./install.chezscheme.sps ../lib
;; Source origin: https://github.com/arcfide/chez-srfi
;; Please refer to project site for full credits and original code.
;;;;;; File header: %3a99/records/procedural.larceny.sls
(library (srfi :99 records procedural)
  (export make-rtd rtd? rtd-constructor rtd-predicate
    rtd-accessor rtd-mutator)
  (import (err5rs records procedural)))
