;; DO NOT EDIT THIS FILE!!
;; This inlined chez-srfi library code is autogenerated using command:
;; $ ./install.chezscheme.sps ../vendor
;; Source origin: https://github.com/arcfide/chez-srfi
;; Please refer to project site for full credits and original code.
;;;;;; File header: %3a6.sls
#!r6rs
;; Automatically generated by private/make-aliased-libraries.sps
(library (purs runtime srfi :6)
  (export
    get-output-string
    open-input-string
    open-output-string)
  (import (purs runtime srfi :6 basic-string-ports)))
