name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install current Bash on macOS
        if: runner.os == 'macOS'
        run: brew install bash

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.yaml') }}
          path: |
            .spago
            output

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build the project
        run: |
          nix develop -c bash -c "spago build"

      - name: Run tests
        run: |
          nix develop -c bash -c "npm run test"

      - name: Check Formatting
        run: |
          nix develop -c bash -c "purs-tidy check src test"
