name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.15.8"
          purs-tidy: "0.9.2"
          psa: "0.8.2"
          spago: "0.20.9"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Set up Node toolchain
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build the project
        run: |
          spago build --purs-args "--censor-lib --strict"

      - name: Run tests 
        run: |
          spago -x test.dhall test

      - name: Check Formatting
        if: runner.os == 'Linux'
        run: |
          purs-tidy check src test
