name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install current Bash on macOS
        if: runner.os == 'macOS'
        run: brew install bash

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.yaml') }}
          path: |
            .spago
            output

      - name: Set up Node toolchain
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Build the project
        run: |
          nix-shell --run "spago build"

      - name: Run tests
        run: |
          nix-shell --run "spago test"

      - name: Check Formatting
        run: |
          nix-shell --run "purs-tidy check src test"
